/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/after-register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/dokter`; params?: Router.UnknownInputParams; } | { pathname: `/icons`; params?: Router.UnknownInputParams; } | { pathname: `/pasien${'/(tabs)'}` | `/pasien`; params?: Router.UnknownInputParams; } | { pathname: `/pasien${'/(tabs)'}/profile` | `/pasien/profile`; params?: Router.UnknownInputParams; } | { pathname: `/pasien${'/(tabs)'}/riwayat` | `/pasien/riwayat`; params?: Router.UnknownInputParams; } | { pathname: `/pasien/daftar-kunjungan`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi/step1`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi/step2`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi/step3`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi-status/selesai`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/after-register`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/dokter`; params?: Router.UnknownOutputParams; } | { pathname: `/icons`; params?: Router.UnknownOutputParams; } | { pathname: `/pasien${'/(tabs)'}` | `/pasien`; params?: Router.UnknownOutputParams; } | { pathname: `/pasien${'/(tabs)'}/profile` | `/pasien/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/pasien${'/(tabs)'}/riwayat` | `/pasien/riwayat`; params?: Router.UnknownOutputParams; } | { pathname: `/pasien/daftar-kunjungan`; params?: Router.UnknownOutputParams; } | { pathname: `/verifikasi/step1`; params?: Router.UnknownOutputParams; } | { pathname: `/verifikasi/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/verifikasi/step3`; params?: Router.UnknownOutputParams; } | { pathname: `/verifikasi-status/selesai`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/after-register${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/dokter${`?${string}` | `#${string}` | ''}` | `/icons${`?${string}` | `#${string}` | ''}` | `/pasien${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/pasien${`?${string}` | `#${string}` | ''}` | `/pasien${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/pasien/profile${`?${string}` | `#${string}` | ''}` | `/pasien${'/(tabs)'}/riwayat${`?${string}` | `#${string}` | ''}` | `/pasien/riwayat${`?${string}` | `#${string}` | ''}` | `/pasien/daftar-kunjungan${`?${string}` | `#${string}` | ''}` | `/verifikasi/step1${`?${string}` | `#${string}` | ''}` | `/verifikasi/step2${`?${string}` | `#${string}` | ''}` | `/verifikasi/step3${`?${string}` | `#${string}` | ''}` | `/verifikasi-status/selesai${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/after-register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/dokter`; params?: Router.UnknownInputParams; } | { pathname: `/icons`; params?: Router.UnknownInputParams; } | { pathname: `/pasien${'/(tabs)'}` | `/pasien`; params?: Router.UnknownInputParams; } | { pathname: `/pasien${'/(tabs)'}/profile` | `/pasien/profile`; params?: Router.UnknownInputParams; } | { pathname: `/pasien${'/(tabs)'}/riwayat` | `/pasien/riwayat`; params?: Router.UnknownInputParams; } | { pathname: `/pasien/daftar-kunjungan`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi/step1`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi/step2`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi/step3`; params?: Router.UnknownInputParams; } | { pathname: `/verifikasi-status/selesai`; params?: Router.UnknownInputParams; };
    }
  }
}
